### ISSUE TITLE
Crash in 0.6.3

### ISSUE THREAD

**Issue by w3sip** [docopt/docopt.cpp#138] opened 2020-10-12 21:11 UTC
The crash happens both in 0.6.2 and the latest 0.6.3. The attached package can be used to illustrate it. 
Seems to only happen on Windows. Removing leading spaces to the options seems to work as a temporary workaround.

[docopt.zip](https://github.com/docopt/docopt.cpp/files/5367494/docopt.zip)

**Comment by jaredgrubb** [comment] 2020-10-14 15:29
Are you using Boost regex engine? You're probably hitting a known bug in the MSVC regex implementation (#49)

**Comment by stanislavlyalin** [comment] 2021-04-23 08:22
Changing std::regex to boost::regex solves this issue on Windows.

**Comment by jaredgrubb** [comment] 2021-04-24 15:19
Ok, thanks for confirming. That would make this a duplicate of #49 then.

**Closed** 2021-04-24 15:19 UTC
Labels: duplicate
