### ISSUE TITLE
MS Visual Studio 2019 reports missing include of stdexcept in docopt_value.h

### ISSUE THREAD

**Issue by Thomas-Haase** [docopt/docopt.cpp#108] opened 2019-03-15 11:35 UTC
The code does not compile with MS Visual Studio Professional 2019 Preview (Version 16.0.0 Preview 4.2). It reports missing include of stdexcept in docopt_value.h.

**Comment by rdeterre** [comment] 2020-03-25 15:02
If I'm not mistaken, this could be closed now, the problem is fixed in master

**Comment by jaredgrubb** [comment] 2020-03-28 00:45
Indeed! Thanks for that notice :) @Thomas-Haase please let me know if your issue is not actually resolved.

**Closed by jaredgrubb** 2020-03-28 00:45 UTC
Labels: needs-patch, simple-fix

**Comment by Thomas-Haase** [comment] 2020-03-30 07:35
Thanks. Yes, the issue is resolved.
